name: Generate Code with ChatGPT on Issue Creation
on:
  issues:
    types: [opened, reopened]

jobs:
  checkout-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Print Issue Information
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
        run: |
          echo "Issue Number: $ISSUE_NUMBER"
          echo "Issue Title: $ISSUE_TITLE"
          echo "Issue Body: $ISSUE_BODY"
          echo "Issue Assignees: $ISSUE_ASSIGNEES"
          echo "Issue Labels: $ISSUE_LABELS"
  
      - name: Generate Code with ChatGPT
        if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
        working-directory: ./scripts
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          chmod +x script.sh
          ./script.sh ${{ env.GITHUB_TOKEN }} ${{ env.REPOSITORY }} ${{ env.ISSUE_NUMBER}} ${{ env.OPENAI_API_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: scripts/autocoder-bot/**
          if-no-files-found: error # optional, default is warn
          retention-days: 1

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact

      - name: Display Generated Code using the ls command
        run: ls -R